package:
  name: vtk
  version: "7.1.0"

source:
  fn: VTK-7.1.0.tar.gz
  url: http://www.vtk.org/files/release/7.1/VTK-7.1.0.tar.gz
  sha1: d3701ff23cb935e107e00174cf75d45a7a9cbdda

build:
  number: 0

requirements:
  build:
   - python
   - cmake
   - hdf5

  run:
   - python
   - hdf5

test:
  requires:
    - numpy
    - pillow

  imports:
    - vtk

about:
  home: http://www.vtk.org
  license: BSD
